name: health-detector

on:
# push:
#   branches:
#      - main
 schedule:
   - cron: "20 * * * *"
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute check
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python scripts/health_check.py $URL
        env:
          URL: ${{ secrets.ONE_SHOT_PLANTUML_HEALTH_ROBOT_TOKEN }}
